project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  
website:
  site-url: https://www.example.com
  title: "Brendan Galdo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: https://thegreatgaldini.substack.com/
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

