project:
  type: website
  output-dir: docs
  
website:
  site-url: https://www.brendangaldo.com
  title: "Brendan Galdo"
  navbar:
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME
